# -*- coding: utf-8 -*-
"""Prodigy_Trackcode_Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WcEOP8CrMIcmVGVHD1h4zGIvhgcov7Lw
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/tested.csv')
df

df.head(10)

age=df['Age'].dropna()

df.info()

plt.figure(figsize=(10, 6))
plt.hist(age, bins=30, edgecolor='k', alpha=0.7)
plt.title('Age Distribution of Titanic Passengers')
plt.xlabel('Age')
plt.ylabel('Number of Passengers')
plt.grid(axis='y', alpha=0.75)
plt.show()